#!/usr/bin/env python3
"""Bake the kept vocabulary's decode strings into a firmware header.

Row order MUST match quantize.py: sorted(keep_ids ∪ forced 0..258). Both files
derive it the same way; the flash script cross-checks the row count against the
pack header so a stale header cannot ship.

  python3 gen_vocab_header.py --tokenizer tokenizer.bin --keep keep_ids.txt \
      --out firmware/generated/vocab.h
"""

import argparse
import struct
from pathlib import Path


def load_tokens(path):
    raw = Path(path).read_bytes()
    off = 4
    toks = []
    while off < len(raw):
        (ln,) = struct.unpack_from("<i", raw, off + 4)
        s = raw[off + 8:off + 8 + ln]
        toks.append(s)
        off += 8 + ln
    return toks


def decode_bytes(s):
    """Token text as the exact bytes the device should print. Byte-fallback
    tokens (<0xXX>) become the raw byte; specials print nothing."""
    if s in (b"<unk>", b"<s>", b"</s>", b""):
        return b""
    if len(s) == 6 and s.startswith(b"<0x") and s.endswith(b">"):
        return bytes([int(s[3:5], 16)])
    return s


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tokenizer", required=True)
    ap.add_argument("--keep", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    toks = load_tokens(args.tokenizer)
    keep = sorted({int(x) for x in Path(args.keep).read_text().split()} |
                  set(range(0, min(259, len(toks)))))

    blob = bytearray()
    offs = [0]
    for tid in keep:
        blob += decode_bytes(toks[tid])
        offs.append(len(blob))

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as f:
        f.write("// Generated by gen_vocab_header.py: kept-row id -> utf8 bytes.\n")
        f.write("// Row order matches quantize.py (sorted keep ∪ forced 0..258).\n")
        f.write("#ifndef VOCAB_H\n#define VOCAB_H\n#include <stdint.h>\n\n")
        f.write(f"#define VOCAB_N {len(keep)}\n\n")
        f.write(f"static const uint32_t VOCAB_OFF[VOCAB_N + 1] = {{\n")
        for i in range(0, len(offs), 12):
            f.write("  " + " ".join(f"{v}," for v in offs[i:i + 12]) + "\n")
        f.write("};\n\n")
        f.write(f"static const uint8_t VOCAB_BLOB[{max(1, len(blob))}] = {{\n")
        for i in range(0, len(blob), 16):
            f.write("  " + " ".join(f"0x{b:02x}," for b in blob[i:i + 16]) + "\n")
        f.write("};\n\n#endif\n")

    print(f"wrote {out}: {len(keep)} rows, {len(blob)} blob bytes")


if __name__ == "__main__":
    main()
